[package]
name = "packer"
version = "0.1.0"
authors = ["Rexagon <reide740@gmail.com>"]
edition = "2018"

[dependencies]
globwalk = "0.7"
libflate = "0.1"
yaml-rust = "0.4"
byteorder = "1.3"
path-slash = "0.1"
